import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";

const inter = Inter();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased relative bg-black`}>
        <div className="fixed inset-0 z-[-1]">
          <AuroraBackground isFixedBackground />
        </div>
        <main className="relative z-0 h-full">
          {children}
        </main>
      </body>
    </html>
  );
}